### ISSUE TITLE
too many mods to fit on screen

### ISSUE THREAD

**Issue by fadedsanti** [SomeGuy6858/MRMM#2]
if you have too many mods loaded, you cant click some of them at the bottom or the refresh button, maybe add a scroll feature for mods?

**Comment by SomeGuy6858** [comment]
No idea how this flew over my head, I'll fix this, thanks.

**Comment by SomeGuy6858** [comment]
I've fixed it by adding a scroll bar and will be putting out a new release in just a minute, thanks for bringing this up.
